version: "2"
linters:
  default: standard

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

    paths:
      - ".*\\.my\\.go$"
      - ".*_test\\.go$"

run:
  skip-dirs-use-default: true
  skip-dirs:
    - hack
    - vendor
