version: "2"
linters:
  default: standard

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

    rules:
      - linters: [staticcheck]
        path: ".*_tests\\.go$"
        text: "ST1001"

    paths:
      - ".*\\.my\\.go$"
      - ".*_test\\.go$"
      - "hack/"
      - "vendor/"
