version: 2

project_name: gavel

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gavel
    main: ./cmd/gavel/main.go
    binary: gavel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^build:"
      - "^fixup:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

brews:
  - name: gavel
    repository:
      owner: "{{ .Env.GITHUB_OWNER }}"
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/{{ .Env.GITHUB_OWNER }}/gavel
    description: "Gavel - a CLI tool by Flanksource"
    license: "Apache-2.0"
    skip_upload: auto
    dependencies:
      - name: git
    install: |
      bin.install "gavel"
    test: |
      system "#{bin}/gavel", "version"

scoops:
  - name: gavel
    repository:
      owner: "{{ .Env.GITHUB_OWNER }}"
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    directory: bucket
    homepage: https://github.com/{{ .Env.GITHUB_OWNER }}/gavel
    description: "Gavel - a CLI tool by Flanksource"
    license: "Apache-2.0"
    skip_upload: auto

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Version }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:latest-amd64"
      - "ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:latest-arm64"

release:
  github:
    owner: "{{ .Env.GITHUB_OWNER }}"
    name: gavel
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Gavel {{ .Tag }} ({{ .Date }})
  footer: |
    ## Docker Images

    ```bash
    docker pull ghcr.io/{{ .Env.GITHUB_OWNER }}/gavel:{{ .Tag }}
    ```

    ## Installation

    ### Using Go
    ```bash
    go install github.com/{{ .Env.GITHUB_OWNER }}/gavel/cmd/gavel@{{ .Tag }}
    ```

    ### Using Homebrew (macOS/Linux)
    ```bash
    brew install {{ .Env.GITHUB_OWNER }}/tap/gavel
    ```

    ### Using Scoop (Windows)
    ```bash
    scoop bucket add {{ .Env.GITHUB_OWNER }} https://github.com/{{ .Env.GITHUB_OWNER }}/scoop-bucket.git
    scoop install gavel
    ```
