package main

import (
	"errors"
	"fmt"
	"os/exec"
	"strings"

	"github.com/flanksource/captain/pkg/aiflags"
	"github.com/flanksource/clicky"
	commitpkg "github.com/flanksource/gavel/commit"
	prcreate "github.com/flanksource/gavel/pr/create"
	"github.com/flanksource/gavel/pr/model"
	"github.com/spf13/cobra"
)

var (
	prCreateBase     string
	prCreateDraft    bool
	prCreateMainline int
	prCreateRepo     string
	prCreateModel    string
	prCreateNoCache  bool
)

var prCreateCmd = &cobra.Command{
	Use:   "create <SHA> [SHA...]",
	Short: "Cherry-pick commits into a fresh worktree off --base and open a PR",
	Long: `Open a PR from existing commits — the gavel alternative to gh pr create
for the "one commit, one PR" flow.

Cherry-picks each <SHA>, in the order given, into an isolated worktree branched
from --base (default: .gavel.yaml pr.base, else origin/main), so your working
tree is untouched. The PR
title, body, and branch name are generated by an LLM from the commits (never
hand-rolled) — override the model with --model. On a cherry-pick conflict the
worktree is kept with resolve hints; otherwise it is cleaned up automatically.

For committing your current changes and opening a PR in one step, use
'gavel commit -p' instead.

Examples:
  gavel pr create HEAD                 # PR from the tip commit
  gavel pr create abc1234              # PR from a specific commit
  gavel pr create abc1234 def5678      # PR from two commits, picked in order
  gavel pr create HEAD --base main     # branch from a different base
  gavel pr create HEAD --draft         # open as a draft
  gavel pr create <merge-sha> --mainline 1   # cherry-pick a merge commit`,
	SilenceUsage: true,
	Args:         cobra.MinimumNArgs(1),
	RunE:         runPRCreate,
}

func init() {
	prCmd.AddCommand(prCreateCmd)
	prCreateCmd.Flags().StringVar(&prCreateBase, "base", "", "Base ref to branch from (default: .gavel.yaml pr.base, else "+prcreate.DefaultBase+")")
	prCreateCmd.Flags().BoolVar(&prCreateDraft, "draft", false, "Open as draft PR")
	prCreateCmd.Flags().IntVar(&prCreateMainline, "mainline", 0, "Mainline parent for cherry-picking a merge commit (1-based)")
	prCreateCmd.Flags().StringVarP(&prCreateRepo, "repo", "R", "", "GitHub owner/repo or hosted Azure DevOps repository URL (must match origin)")
	prCreateCmd.Flags().StringVar(&prCreateModel, "model", "", "Override the LLM model used for PR title/body/branch")
	prCreateCmd.Flags().BoolVar(&prCreateNoCache, "no-cache", false, "Disable LLM response cache")
}

func runPRCreate(cmd *cobra.Command, args []string) error {
	base, err := prcreate.ResolveBase(".", prCreateBase)
	if err != nil {
		return err
	}
	workDir, err := getWorkingDir()
	if err != nil {
		return fmt.Errorf("resolve working directory: %w", err)
	}
	repoRoot, err := gitRepoRoot(workDir)
	if err != nil {
		return err
	}
	res, err := prcreate.Create(cmd.Context(), repoRoot, prcreate.Input{
		SHAs: args, Base: base, Draft: prCreateDraft, Mainline: prCreateMainline, Repo: prCreateRepo,
		Flags: modelFlagsFromCommand(aiflags.ModelFlags{Model: prCreateModel, NoCache: prCreateNoCache}, cmd),
		Deps:  prcreate.DefaultDeps(),
	})
	var conflict *prcreate.ConflictError
	if errors.As(err, &conflict) {
		printConflictHint(conflict.Worktree, conflict.Branch)
	}
	if err != nil {
		return err
	}
	printPRCreateSummary(res.PR, res.Content)
	openBrowser(res.PR.URL)
	return nil
}

func gitRepoRoot(workDir string) (string, error) {
	out, err := exec.Command("git", "-C", workDir, "rev-parse", "--show-toplevel").Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return "", fmt.Errorf("locate repo root of %s: %s", workDir, strings.TrimSpace(string(exitErr.Stderr)))
		}
		return "", fmt.Errorf("locate repo root of %s: %w", workDir, err)
	}
	return strings.TrimSpace(string(out)), nil
}

func printConflictHint(wtPath, tmpBranch string) {
	t := clicky.Text("cherry-pick conflict; resolve in ", "text-yellow-600").
		Append(wtPath, "font-bold").NewLine().
		Append("  git -C "+wtPath+" cherry-pick --continue", "text-muted").NewLine().
		Append("  git -C "+wtPath+" push -u origin "+tmpBranch, "text-muted").NewLine()
	fmt.Println(t.ANSI())
}

func printPRCreateSummary(created *model.CreatePRResult, content commitpkg.PRContent) {
	t := clicky.Text(fmt.Sprintf("PR #%d", created.Number), "font-bold text-green-600").
		Space().Append(content.Title, "font-bold").NewLine().
		Append(created.URL, "text-muted").NewLine()
	if body := strings.TrimSpace(content.Body); body != "" {
		t = t.NewLine().Append(body, "")
	}
	fmt.Println(t.ANSI())
}
