export const projectStatusResponse = {
  project: { name: 'gavel', dir: '/work/gavel', repos: ['acme/gavel'] },
  workDir: '/work/gavel',
  branch: 'feature/projects',
  files: [
    {
      path: 'one.go',
      state: 'unstaged',
      workKind: 'M',
      adds: 12,
      dels: 3,
      testStatus: { passed: 4, failed: 0, skipped: 0 },
      lintStatus: { errors: 0, warnings: 1, infos: 0 },
      problems: [],
      resultsStale: false,
    },
    {
      path: 'conflicted.go',
      state: 'conflict',
      workKind: 'M',
      adds: 1,
      dels: 1,
      testStatus: { passed: 0, failed: 1, skipped: 0 },
      lintStatus: { errors: 1, warnings: 0, infos: 0 },
      problems: [],
      resultsStale: false,
      conflictReason: 'unmerged',
    },
    {
      path: 'generated/output.log',
      state: 'untracked',
      workKind: '?',
      adds: 8,
      dels: 0,
      testStatus: { passed: 0, failed: 0, skipped: 0 },
      lintStatus: { errors: 0, warnings: 0, infos: 0 },
      problems: [],
      resultsStale: false,
    },
    {
      path: 'generated/cache/data.json',
      state: 'untracked',
      workKind: '?',
      adds: 2,
      dels: 0,
      testStatus: { passed: 0, failed: 0, skipped: 0 },
      lintStatus: { errors: 0, warnings: 0, infos: 0 },
      problems: [],
      resultsStale: false,
    },
  ],
  resultsStale: false,
  action: { running: false },
};
